"""empty message

Revision ID: d9270efbfa2d
Revises: 61d2799e4585
Create Date: 2025-06-03 16:14:40.947302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9270efbfa2d'
down_revision = '61d2799e4585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_text', sa.String(length=120), nullable=False))
        batch_op.drop_column('120')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('120', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('comment_text')

    op.drop_table('follower')
    # ### end Alembic commands ###
